# Generated by Django 5.0.2 on 2024-03-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='is_company',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Check if the Partner is a Organisation not an Individual', verbose_name='is a company'),
        ),
    ]
